name: .Net Objects Publish and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.300
          
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
      - name: Pack
        run: dotnet pack -c Release
      - name: Publish Nuget to GitHub registry
        run: dotnet nuget push ./bin/Release/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${NUGET_TOKEN} --skip-duplicate --no-symbols
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: View Contents
        run: tree
